{
 "title": "pg-promise",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_pool_connections_created_total,instance)"
    }
   },
   { "name": "host", "label": "Host", "query": { "query": "label_values(pg_pool_max,host)" } },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_pool_max,database)"
    }
   },
   {
    "name": "command",
    "label": "Command",
    "query": {
     "query": "label_values(pg_command_duration_seconds_sum,command)"
    }
   },
   {
    "name": "task",
    "label": "Task",
    "query": {
     "query": "label_values(pg_task_duration_seconds_sum,task)"
    }
   },
   {
    "name": "transaction",
    "label": "Transaction",
    "query": {
     "query": "label_values(pg_transaction_duration_seconds_sum,transaction)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disconnected Connections",
   "type": "timeseries",
   "description": "The total number of disconnected connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_client_disconnects_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Disconnected Connections Rate",
   "type": "timeseries",
   "description": "The total number of disconnected connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_client_disconnects_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}[$__rate_interval])) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Errors",
   "type": "timeseries",
   "description": "The total number of connection errors with a database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pg_client_errors_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Errors",
   "type": "timeseries",
   "description": "The total number of connection errors with a database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_client_errors_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}[$__rate_interval])) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "The number of connections that are currently in use.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(pg_pool_active_connections{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}[$__rate_interval])) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Pool Usage",
   "type": "timeseries",
   "description": "Current size of the connection pool, including idle and and in-use members.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_pool_size{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Pool Utilization",
   "type": "timeseries",
   "description": "Current size of the connection pool, including idle and and in-use members.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pg_pool_size{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database) / sum(pg_pool_max{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Waiting Connections",
   "type": "timeseries",
   "description": "The total number of waiting connections.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_pool_waiting_connections{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "timeseries",
   "description": "The total number of idle connections.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_pool_idle_connections{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Pool Max",
   "type": "timeseries",
   "description": "The maximum size of the connection pool.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_pool_max{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Removed Connections Rate",
   "type": "timeseries",
   "description": "The total number of removed connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_pool_connections_removed_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}[$__rate_interval])) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Removed Connections",
   "type": "timeseries",
   "description": "The total number of removed connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_pool_connections_removed_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Errors",
   "type": "timeseries",
   "description": "The total number of connection errors with a database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(pg_pool_errors_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  {
   "title": "Connection Errors Rate",
   "type": "timeseries",
   "description": "The total number of connection errors with a database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_pool_errors_total{instance=~\"$instance\", host=~\"$host\", database=~\"$database\"}[$__rate_interval])) by (instance, host, database)",
     "legendFormat": "{{instance}} - {{host}} - {{database}}"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Commands Latency By Command",
   "type": "timeseries",
   "description": "Average command execution latency.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_command_duration_seconds_sum{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", command=~\"$command\"}[$__rate_interval])) by (instance, host, database, command) / sum(rate(pg_command_duration_seconds_count{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", command=~\"$command\"}[$__rate_interval])) by (instance, host, database, command)",
     "legendFormat": "{{instance}} - {{host}} - {{database}} - {{command}}"
    }
   ]
  },
  {
   "title": "Commands Rate By Command",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_command_duration_seconds_count{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", command=~\"$command\"}[$__rate_interval])) by (instance, host, database, command)",
     "legendFormat": "{{instance}} - {{host}} - {{database}} - {{command}}"
    }
   ]
  },
  {
   "title": "Erroneous Commands Rate By Command",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_command_duration_seconds_count{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", command=~\"$command\", status=\"ERROR\"}[$__rate_interval])) by (instance, host, database, command)",
     "legendFormat": "{{instance}} - {{host}} - {{database}} - {{command}}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_command_duration_seconds_count{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", command=~\"$command\"}) by (instance, host, database, command)",
     "legendFormat": "{{instance}} - {{host}} - {{database}} - {{command}}"
    }
   ]
  },
  {
   "title": "Erroneous Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_command_duration_seconds_count{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", command=~\"$command\", status=\"ERROR\"}) by (instance, host, database, command)",
     "legendFormat": "{{instance}} - {{host}} - {{database}} - {{command}}"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tasks Latency By Task",
     "type": "timeseries",
     "description": "Average task execution latency.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(pg_task_duration_seconds_sum{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", task=~\"$task\"}[$__rate_interval])) by (instance, host, database, task) / sum(rate(pg_task_duration_seconds_count{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", task=~\"$task\"}[$__rate_interval])) by (instance, host, database, task)",
       "legendFormat": "{{instance}} - {{host}} - {{database}} - {{task}}"
      }
     ]
    },
    {
     "title": "Tasks Rate By Task",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(pg_task_duration_seconds_count{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", task=~\"$task\"}[$__rate_interval])) by (instance, host, database, task)",
       "legendFormat": "{{instance}} - {{host}} - {{database}} - {{task}}"
      }
     ]
    },
    {
     "title": "Total Tasks By Task",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(pg_task_duration_seconds_count{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", task=~\"$task\"}) by (instance, host, database, task)",
       "legendFormat": "{{instance}} - {{host}} - {{database}} - {{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true
  },
  {
   "title": "Transaction Latency By Transaction",
   "type": "timeseries",
   "description": "Average transaction execution latency.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_transaction_duration_seconds_sum{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", transaction=~\"$transaction\"}[$__rate_interval])) by (instance, host, database, transaction) / sum(rate(pg_transaction_duration_seconds_count{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", transaction=~\"$transaction\"}[$__rate_interval])) by (instance, host, database, transaction)",
     "legendFormat": "{{instance}} - {{host}} - {{database}} - {{transaction}}"
    }
   ]
  },
  {
   "title": "Transaction Rate By Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(pg_transaction_duration_seconds_count{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", transaction=~\"$transaction\"}[$__rate_interval])) by (instance, host, database, transaction)",
     "legendFormat": "{{instance}} - {{host}} - {{database}} - {{transaction}}"
    }
   ]
  },
  {
   "title": "Total Transactions By Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_transaction_duration_seconds_count{instance=~\"$instance\", host=~\"$host\", database=~\"$database\", transaction=~\"$transaction\"}) by (instance, host, database, transaction)",
     "legendFormat": "{{instance}} - {{host}} - {{database}} - {{transaction}}"
    }
   ]
  }
 ]
}