name: 'Continuous Integration'
on:
  push:
    branches:
      - 'main'
      - 'renovate/**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  ci:
    uses:
      christiangalsterer/github-actions/blob/main/.github/workflows/node_ci.yaml