name: Snyk

on:
  push:
    branches: 
      - 'main'
      - 'renovate/**'
      - 'disabled_synk'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'

jobs:
  snyk:
    uses:
      christiangalsterer/github-actions/.github/workflows/node_snyk.yaml@main